In [1]:
import pandas as pd
import random
import itertools
import numpy as np

In [3]:
df_daftar_nama = pd.read_excel('../Data/Nama untuk sistem (1).xlsx')

# Clean teks
def clean_teks(teks):
    teks = ' '.join(teks.split())
    return teks

df_daftar_nama['Nama'] = df_daftar_nama['Nama'].apply(clean_teks)

df_daftar_nama = df_daftar_nama[['Nama']].drop_duplicates().reset_index(drop=True)

df_daftar_nama = df_daftar_nama.rename(columns={'Nama':'name'})

df_daftar_nama

                                          name
0                              Adi Nugroho SST
1                             Adwi Hastuti SST
2                          Alvina Clarissa SST
3            Ana Lailatul Fitriyani S.Tr.Stat.
4                Bayu Dwi Kurniawan S.Tr.Stat.
5                             Chairul Anam SAP
6               Dede Yoga Paramartha S.Tr.Stat
7                   Dewi Krismawati SST, M.T.I
8                     Dewi Lestari Amaliah SST
9                    Dewi Widyawati S.Tr.Stat.
10              Dhiar Niken Larasati SST, M.E.
11                    Didit Puji Hariyanto SST
12          Dimas Hari Santoso S.Si, M.Ec, M.E
13             Dyah Retno Prihatinningsih B.St
14           Ema Tusianti SST, SAB, M.T., M.Sc
15        Erna Yulianingsih SST, M.Appl.Ecmets
16                           Ety Kurniati S.ST
17             Fadlilah Nur Hidayah S.Tr.Stat.
18             Farhan Anshari Arsyi S.Tr.Stat.
19         Fenny Afifatul Awwaliyah S.Tr.Stat.
20               Henri Asri Reagan SST., M.Si.
21   I Gusti Ngurah Agung Rama Gunawan SST.,MT
22                I Nyoman Setiawan S.Tr.Stat.
23                     Indah Budiati SST, M.Si
24         Julita Lovitawati Br. Aritonang SST
25                        Kasiful Aprianto SST
26                     Khairunnisah SST, M.S.E
27  Lestyowati Endang Widyantari S.Si, M.Kesos
28            Maria Audrey Widiatma S.Tr.Stat.
29                           Maulana Faris SST
30                          Muhammad Ihsan SST
31                       Nensi Fitria Deli SST
32                    Nia Setiyawati SST, M.Sc
33            Nur Putri Cahyo Utami SST, M.P.P
34              Nurarifin SST, M.Ec.Dev, M.Ec.
35                  Nurbaety Setram S.Si, M.S.
36            Putri Wahyu Handayani SST, M.S.E
37                           Ranu Yulianto SST
38                   Rerta Mastiani S.Si, M.Si
39                      Ria Noviana S.Tr.Stat.
40                         Risyanto S.Si, M.Si
41               Sa'ad Tazkiahtu Dienulloh SST
42            Satria Bagus Panuntun S.Tr.Stat.
43                      Sofaria Ayuni S.Si, MM
44                         Sri Hartini MPS, MA
45                 Sukmasari Dewanti SST, M.Sc
46               Synthia Natalia Kristiani SST
47                       Syukriyah Delyana SST
48                Tika Meilaningsih S.Tr.Stat.
49                   Usman Bustaman S.Si, M.Sc
50               Wahyu Calvin Frans Mariel SST
51                      Wisnu Winardi SST, ME.
52                Yeshri Rahayu S.Si, M.Sc, MT
53                  Yohanes Eki Apriliawan SST
54                            Yoyo Karyono SST
55              Zulfa Hidayah Satria Putri SST

In [4]:
nama = 'Indah Budiati SST, M.Si'

# CLEAN NAMA TO GET USERNAME

def get_username(nama):
    list_nama = nama.split(' ')

    username = []
    for nama in list_nama:
        if '.' in nama or ',' in nama:
            pass
        elif nama.isupper():
            pass
        else:
            username.append(nama.lower())

    username = '_'.join(username)

    return username

df_daftar_nama['username'] = df_daftar_nama['name'].apply(get_username)

df_daftar_nama.to_csv('../Data/list_username.csv', sep = ';', index=False)
df_daftar_nama

,name,username
0,Adi Nugroho SST,adi_nugroho
1,Adwi Hastuti SST,adwi_hastuti
2,Alvina Clarissa SST,alvina_clarissa
3,Ana Lailatul Fitriyani S.Tr.Stat.,ana_lailatul_fitriyani
4,Bayu Dwi Kurniawan S.Tr.Stat.,bayu_dwi_kurniawan
5,Chairul Anam SAP,chairul_anam
6,Dede Yoga Paramartha S.Tr.Stat,dede_yoga_paramartha
7,"Dewi Krismawati SST, M.T.I",dewi_krismawati
8,Dewi Lestari Amaliah SST,dewi_lestari_amaliah
9,Dewi Widyawati S.Tr.Stat.,dewi_widyawati
10,"Dhiar Niken Larasati SST, M.E.",dhiar_niken_larasati
11,Didit Puji Hariyanto SST,didit_puji_hariyanto
12,"Dimas Hari Santoso S.Si, M.Ec, M.E",dimas_hari_santoso
13,Dyah Retno Prihatinningsih B.St,dyah_retno_prihatinningsih
14,"Ema Tusianti SST, SAB, M.T., M.Sc",ema_tusianti
15,"Erna Yulianingsih SST, M.Appl.Ecmets",erna_yulianingsih
16,Ety Kurniati S.ST,ety_kurniati
17,Fadlilah Nur Hidayah S.Tr.Stat.,fadlilah_nur_hidayah
18,Farhan Anshari Arsyi S.Tr.Stat.,farhan_anshari_arsyi
19,Fenny Afifatul Awwaliyah S.Tr.Stat.,fenny_afifatul_awwaliyah
20,"Henri Asri Reagan SST., M.Si.",henri_asri_reagan
21,"I Gusti Ngurah Agung Rama Gunawan SST.,MT",gusti_ngurah_agung_rama_gunawan
22,I Nyoman Setiawan S.Tr.Stat.,nyoman_setiawan
23,"Indah Budiati SST, M.Si",indah_budiati
24,Julita Lovitawati Br. Aritonang SST,julita_lovitawati_aritonang
25,Kasiful Aprianto SST,kasiful_aprianto
26,"Khairunnisah SST, M.S.E",khairunnisah
27,"Lestyowati Endang Widyantari S.Si, M.Kesos",lestyowati_endang_widyantari
28,Maria Audrey Widiatma S.Tr.Stat.,maria_audrey_widiatma
29,Maulana Faris SST,maulana_faris
30,Muhammad Ihsan SST,muhammad_ihsan
31,Nensi Fitria Deli SST,nensi_fitria_deli
32,"Nia Setiyawati SST, M.Sc",nia_setiyawati
33,"Nur Putri Cahyo Utami SST, M.P.P",nur_putri_cahyo_utami
34,"Nurarifin SST, M.Ec.Dev, M.Ec.",nurarifin
35,"Nurbaety Setram S.Si, M.S.",nurbaety_setram
36,"Putri Wahyu Handayani SST, M.S.E",putri_wahyu_handayani
37,Ranu Yulianto SST,ranu_yulianto
38,"Rerta Mastiani S.Si, M.Si",rerta_mastiani
39,Ria Noviana S.Tr.Stat.,ria_noviana
40,"Risyanto S.Si, M.Si",risyanto
41,Sa'ad Tazkiahtu Dienulloh SST,sa'ad_tazkiahtu_dienulloh
42,Satria Bagus Panuntun S.Tr.Stat.,satria_bagus_panuntun
43,"Sofaria Ayuni S.Si, MM",sofaria_ayuni
44,"Sri Hartini MPS, MA",sri_hartini
45,"Sukmasari Dewanti SST, M.Sc",sukmasari_dewanti
46,Synthia Natalia Kristiani SST,synthia_natalia_kristiani
47,Syukriyah Delyana SST,syukriyah_delyana
48,Tika Meilaningsih S.Tr.Stat.,tika_meilaningsih
49,"Usman Bustaman S.Si, M.Sc",usman_bustaman
50,Wahyu Calvin Frans Mariel SST,wahyu_calvin_frans_mariel
51,"Wisnu Winardi SST, ME.",wisnu_winardi
52,"Yeshri Rahayu S.Si, M.Sc, MT",yeshri_rahayu
53,Yohanes Eki Apriliawan SST,yohanes_eki_apriliawan
54,Yoyo Karyono SST,yoyo_karyono
55,Zulfa Hidayah Satria Putri SST,zulfa_hidayah_satria_putri