In [1]:
import pandas as pd
import random
import itertools
import numpy as np

In [2]:
df_daftar_nama = pd.read_excel('../Data/Nama untuk sistem (1).xlsx')

# Clean nama
def clean_teks(teks):
    teks = ' '.join(teks.split())
    return teks

df_daftar_nama['Nama'] = df_daftar_nama['Nama'].apply(clean_teks)
df_daftar_nama['Tim'] = df_daftar_nama['Tim'].apply(clean_teks)
df_daftar_nama['Jabatan'] = df_daftar_nama['Jabatan'].apply(clean_teks)

df_daftar_nama

,Nama,Tim,Jabatan
0,Adi Nugroho SST,Analisis Statistik,Anggota Tim
1,Adwi Hastuti SST,Tim penyusun publikasi inkesra,Anggota Tim
2,Adwi Hastuti SST,Tim penyusun publikasi sdgs,Anggota Tim
3,Alvina Clarissa SST,Analisis Statistik,Anggota Tim
4,Ana Lailatul Fitriyani S.Tr.Stat.,Tim Analisis dan Diseminasi Big Data(Data Insi...,Anggota Tim
...,...,...,...
135,Yohanes Eki Apriliawan SST,Pengukuran Kualitas,Anggota Tim
136,Yohanes Eki Apriliawan SST,Pembinaan statistik sektoral,Anggota Tim
137,Yoyo Karyono SST,Analisis Statistik,Ketua Tim
138,Zulfa Hidayah Satria Putri SST,Tim Analisis dan Diseminasi Big Data(Data Insi...,Anggota Tim
139,Zulfa Hidayah Satria Putri SST,Tim Pengembangan Indikator dan Penjaminan Kual...,Anggota Tim

In [3]:
# Daftar Tim dan daftar tim
daftar_tim = df_daftar_nama['Tim'].drop_duplicates().to_list()
daftar_nama = df_daftar_nama['Nama'].drop_duplicates().to_list()

In [85]:
# Coba satu tim

df_tim = df_daftar_nama[df_daftar_nama['Tim'] == 'Analisis Statistik'].reset_index(drop=True)

for index, row in df_tim.iterrows():
    nama = row['Nama']
    tim = row['Tim']
    jabatan = row['Jabatan']

    ## Jika ANGGOTA TIM
    if jabatan == 'Anggota Tim':
        # List rekan kerja
        list_rekan_kerja = df_tim[(df_tim['Nama'] != nama) & (df_tim['Jabatan'] == 'Anggota Tim')]['Nama'].to_list()
        # List atasan
        list_atasan = df_tim[df_tim['Jabatan'] == 'Ketua Tim']['Nama'].to_list()

        # Memilih 4 sampel random dari list rekan kerja dan 1 sampel rando dari list atasan
        try:
            sampel_rekan_kerja = random.sample(list_rekan_kerja, 4)
            sampel_atasan = random.sample(list_atasan, 1)
        except:
            sampel_rekan_kerja = random.sample(list_rekan_kerja, len(list_rekan_kerja))
            sampel_atasan = random.sample(list_atasan, len(list_atasan))

        # Menggabungkan kedua sampel
        sampel_terpilih = sampel_atasan + sampel_rekan_kerja

    elif jabatan == 'Ketua Tim':
        # List bawahan
        list_bawahan = df_tim[(df_tim['Nama'] != nama) & (df_tim['Jabatan'] == 'Anggota Tim')]['Nama'].to_list()

        # Memilih 5 sampel random dari list bawahan
        try:
            sampel_bawahan = random.sample(list_bawahan, 5)
        except:
            sampel_bawahan = random.sample(list_bawahan, len(list_bawahan))

        # Menggabungkan kedua sampel
        sampel_terpilih = sampel_bawahan

    for sampel in sampel_terpilih:
        baris = [nama, tim, jabatan, sampel]

        print(baris)

    # print(f'{nama} - {jabatan}')
    # # print(list_rekan_kerja)
    # # print(list_atasan)
    # print(sampel_terpilih)
    # print('')

['Wisnu Winardi SST, ME.', 'Analisis Statistik', 'Ketua Tim', 'Alvina Clarissa SST']
['Wisnu Winardi SST, ME.', 'Analisis Statistik', 'Ketua Tim', 'Fenny Afifatul Awwaliyah S.Tr.Stat.']
['Wisnu Winardi SST, ME.', 'Analisis Statistik', 'Ketua Tim', 'Bayu Dwi Kurniawan S.Tr.Stat.']
['Wisnu Winardi SST, ME.', 'Analisis Statistik', 'Ketua Tim', 'Dede Yoga Paramartha S.Tr.Stat']
['Wisnu Winardi SST, ME.', 'Analisis Statistik', 'Ketua Tim', 'Dimas Hari Santoso S.Si, M.Ec, M.E']
['Yoyo Karyono SST', 'Analisis Statistik', 'Ketua Tim', 'Dewi Widyawati S.Tr.Stat.']
['Yoyo Karyono SST', 'Analisis Statistik', 'Ketua Tim', 'Syukriyah Delyana SST']
['Yoyo Karyono SST', 'Analisis Statistik', 'Ketua Tim', 'Bayu Dwi Kurniawan S.Tr.Stat.']
['Yoyo Karyono SST', 'Analisis Statistik', 'Ketua Tim', 'Dyah Retno Prihatinningsih B.St']
['Yoyo Karyono SST', 'Analisis Statistik', 'Ketua Tim', 'Nur Putri Cahyo Utami SST, M.P.P']
['Dyah Retno Prihatinningsih B.St', 'Analisis Statistik', 'Anggota Tim', 'I Gusti Ngurah Agung Rama Gunawan SST.,MT']
['Dyah Retno Prihatinningsih B.St', 'Analisis Statistik', 'Anggota Tim', 'Syukriyah Delyana SST']
['Dyah Retno Prihatinningsih B.St', 'Analisis Statistik', 'Anggota Tim', 'Nur Putri Cahyo Utami SST, M.P.P']
['Dyah Retno Prihatinningsih B.St', 'Analisis Statistik', 'Anggota Tim', 'Alvina Clarissa SST']
['Dyah Retno Prihatinningsih B.St', 'Analisis Statistik', 'Anggota Tim', 'Bayu Dwi Kurniawan S.Tr.Stat.']
['Ema Tusianti SST, SAB, M.T., M.Sc', 'Analisis Statistik', 'Ketua Tim', 'Dimas Hari Santoso S.Si, M.Ec, M.E']
['Ema Tusianti SST, SAB, M.T., M.Sc', 'Analisis Statistik', 'Ketua Tim', 'Nur Putri Cahyo Utami SST, M.P.P']
['Ema Tusianti SST, SAB, M.T., M.Sc', 'Analisis Statistik', 'Ketua Tim', 'Dede Yoga Paramartha S.Tr.Stat']
['Ema Tusianti SST, SAB, M.T., M.Sc', 'Analisis Statistik', 'Ketua Tim', 'Dewi Widyawati S.Tr.Stat.']
['Ema Tusianti SST, SAB, M.T., M.Sc', 'Analisis Statistik', 'Ketua Tim', 'Fenny Afifatul Awwaliyah S.Tr.Stat.']
['I Gusti Ngurah Agung Rama Gunawan SST.,MT', 'Analisis Statistik', 'Ketua Tim', 'Fenny Afifatul Awwaliyah S.Tr.Stat.']
['I Gusti Ngurah Agung Rama Gunawan SST.,MT', 'Analisis Statistik', 'Ketua Tim', 'Dimas Hari Santoso S.Si, M.Ec, M.E']
['I Gusti Ngurah Agung Rama Gunawan SST.,MT', 'Analisis Statistik', 'Ketua Tim', 'Bayu Dwi Kurniawan S.Tr.Stat.']
['I Gusti Ngurah Agung Rama Gunawan SST.,MT', 'Analisis Statistik', 'Ketua Tim', 'Syukriyah Delyana SST']
['I Gusti Ngurah Agung Rama Gunawan SST.,MT', 'Analisis Statistik', 'Ketua Tim', 'Adi Nugroho SST']
['Dimas Hari Santoso S.Si, M.Ec, M.E', 'Analisis Statistik', 'Anggota Tim', 'I Gusti Ngurah Agung Rama Gunawan SST.,MT']
['Dimas Hari Santoso S.Si, M.Ec, M.E', 'Analisis Statistik', 'Anggota Tim', 'Dyah Retno Prihatinningsih B.St']
['Dimas Hari Santoso S.Si, M.Ec, M.E', 'Analisis Statistik', 'Anggota Tim', 'Fenny Afifatul Awwaliyah S.Tr.Stat.']
['Dimas Hari Santoso S.Si, M.Ec, M.E', 'Analisis Statistik', 'Anggota Tim', 'Dewi Widyawati S.Tr.Stat.']
['Dimas Hari Santoso S.Si, M.Ec, M.E', 'Analisis Statistik', 'Anggota Tim', 'Syukriyah Delyana SST']
['Adi Nugroho SST', 'Analisis Statistik', 'Anggota Tim', 'Yoyo Karyono SST']
['Adi Nugroho SST', 'Analisis Statistik', 'Anggota Tim', 'Alvina Clarissa SST']
['Adi Nugroho SST', 'Analisis Statistik', 'Anggota Tim', 'Nur Putri Cahyo Utami SST, M.P.P']
['Adi Nugroho SST', 'Analisis Statistik', 'Anggota Tim', 'Syukriyah Delyana SST']
['Adi Nugroho SST', 'Analisis Statistik', 'Anggota Tim', 'Dyah Retno Prihatinningsih B.St']
['Nur Putri Cahyo Utami SST, M.P.P', 'Analisis Statistik', 'Anggota Tim', 'Wisnu Winardi SST, ME.']
['Nur Putri Cahyo Utami SST, M.P.P', 'Analisis Statistik', 'Anggota Tim', 'Dyah Retno Prihatinningsih B.St']
['Nur Putri Cahyo Utami SST, M.P.P', 'Analisis Statistik', 'Anggota Tim', 'Adi Nugroho SST']
['Nur Putri Cahyo Utami SST, M.P.P', 'Analisis Statistik', 'Anggota Tim', 'Dede Yoga Paramartha S.Tr.Stat']
['Nur Putri Cahyo Utami SST, M.P.P', 'Analisis Statistik', 'Anggota Tim', 'Dewi Widyawati S.Tr.Stat.']
['Syukriyah Delyana SST', 'Analisis Statistik', 'Anggota Tim', 'Yoyo Karyono SST']
['Syukriyah Delyana SST', 'Analisis Statistik', 'Anggota Tim', 'Fenny Afifatul Awwaliyah S.Tr.Stat.']
['Syukriyah Delyana SST', 'Analisis Statistik', 'Anggota Tim', 'Dimas Hari Santoso S.Si, M.Ec, M.E']
['Syukriyah Delyana SST', 'Analisis Statistik', 'Anggota Tim', 'Dede Yoga Paramartha S.Tr.Stat']
['Syukriyah Delyana SST', 'Analisis Statistik', 'Anggota Tim', 'Dewi Widyawati S.Tr.Stat.']
['Alvina Clarissa SST', 'Analisis Statistik', 'Anggota Tim', 'I Gusti Ngurah Agung Rama Gunawan SST.,MT']
['Alvina Clarissa SST', 'Analisis Statistik', 'Anggota Tim', 'Fenny Afifatul Awwaliyah S.Tr.Stat.']
['Alvina Clarissa SST', 'Analisis Statistik', 'Anggota Tim', 'Adi Nugroho SST']
['Alvina Clarissa SST', 'Analisis Statistik', 'Anggota Tim', 'Dimas Hari Santoso S.Si, M.Ec, M.E']
['Alvina Clarissa SST', 'Analisis Statistik', 'Anggota Tim', 'Nur Putri Cahyo Utami SST, M.P.P']
['Dede Yoga Paramartha S.Tr.Stat', 'Analisis Statistik', 'Anggota Tim', 'Yoyo Karyono SST']
['Dede Yoga Paramartha S.Tr.Stat', 'Analisis Statistik', 'Anggota Tim', 'Dimas Hari Santoso S.Si, M.Ec, M.E']
['Dede Yoga Paramartha S.Tr.Stat', 'Analisis Statistik', 'Anggota Tim', 'Alvina Clarissa SST']
['Dede Yoga Paramartha S.Tr.Stat', 'Analisis Statistik', 'Anggota Tim', 'Adi Nugroho SST']
['Dede Yoga Paramartha S.Tr.Stat', 'Analisis Statistik', 'Anggota Tim', 'Fenny Afifatul Awwaliyah S.Tr.Stat.']
['Dewi Widyawati S.Tr.Stat.', 'Analisis Statistik', 'Anggota Tim', 'I Gusti Ngurah Agung Rama Gunawan SST.,MT']
['Dewi Widyawati S.Tr.Stat.', 'Analisis Statistik', 'Anggota Tim', 'Dyah Retno Prihatinningsih B.St']
['Dewi Widyawati S.Tr.Stat.', 'Analisis Statistik', 'Anggota Tim', 'Dimas Hari Santoso S.Si, M.Ec, M.E']
['Dewi Widyawati S.Tr.Stat.', 'Analisis Statistik', 'Anggota Tim', 'Adi Nugroho SST']
['Dewi Widyawati S.Tr.Stat.', 'Analisis Statistik', 'Anggota Tim', 'Syukriyah Delyana SST']
['Fenny Afifatul Awwaliyah S.Tr.Stat.', 'Analisis Statistik', 'Anggota Tim', 'Yoyo Karyono SST']
['Fenny Afifatul Awwaliyah S.Tr.Stat.', 'Analisis Statistik', 'Anggota Tim', 'Dewi Widyawati S.Tr.Stat.']
['Fenny Afifatul Awwaliyah S.Tr.Stat.', 'Analisis Statistik', 'Anggota Tim', 'Dede Yoga Paramartha S.Tr.Stat']
['Fenny Afifatul Awwaliyah S.Tr.Stat.', 'Analisis Statistik', 'Anggota Tim', 'Nur Putri Cahyo Utami SST, M.P.P']
['Fenny Afifatul Awwaliyah S.Tr.Stat.', 'Analisis Statistik', 'Anggota Tim', 'Dyah Retno Prihatinningsih B.St']
['Bayu Dwi Kurniawan S.Tr.Stat.', 'Analisis Statistik', 'Anggota Tim', 'Wisnu Winardi SST, ME.']
['Bayu Dwi Kurniawan S.Tr.Stat.', 'Analisis Statistik', 'Anggota Tim', 'Alvina Clarissa SST']
['Bayu Dwi Kurniawan S.Tr.Stat.', 'Analisis Statistik', 'Anggota Tim', 'Dewi Widyawati S.Tr.Stat.']
['Bayu Dwi Kurniawan S.Tr.Stat.', 'Analisis Statistik', 'Anggota Tim', 'Nur Putri Cahyo Utami SST, M.P.P']
['Bayu Dwi Kurniawan S.Tr.Stat.', 'Analisis Statistik', 'Anggota Tim', 'Dimas Hari Santoso S.Si, M.Ec, M.E']

In [4]:
# UNTUK SEMUA TIM

list_data = []
for tim in daftar_tim:
    print(f'Pengerjaan {tim}')
    df_tim = df_daftar_nama[df_daftar_nama['Tim'] == tim].reset_index(drop=True)

    for index, row in df_tim.iterrows():
        nama = row['Nama']
        tim = row['Tim']
        jabatan = row['Jabatan']

        ## Jika ANGGOTA TIM
        if jabatan == 'Anggota Tim':
            # List rekan kerja
            list_rekan_kerja = df_tim[(df_tim['Nama'] != nama) & (df_tim['Jabatan'] == 'Anggota Tim')]['Nama'].to_list()
            # List atasan
            list_atasan = df_tim[df_tim['Jabatan'] == 'Ketua Tim']['Nama'].to_list()

            # Memilih 4 sampel random dari list rekan kerja dan 1 sampel rando dari list atasan
            try:
                sampel_rekan_kerja = random.sample(list_rekan_kerja, 4)
                sampel_atasan = random.sample(list_atasan, 1)
            except:
                sampel_rekan_kerja = random.sample(list_rekan_kerja, len(list_rekan_kerja))
                sampel_atasan = random.sample(list_atasan, len(list_atasan))

            # Menggabungkan kedua sampel
            sampel_terpilih = sampel_atasan + sampel_rekan_kerja

        elif jabatan == 'Ketua Tim':
            # List bawahan
            list_bawahan = df_tim[(df_tim['Nama'] != nama) & (df_tim['Jabatan'] == 'Anggota Tim')]['Nama'].to_list()

            # Memilih 5 sampel random dari list bawahan
            try:
                sampel_bawahan = random.sample(list_bawahan, 5)
            except:
                sampel_bawahan = random.sample(list_bawahan, len(list_bawahan))

            # Menggabungkan kedua sampel
            sampel_terpilih = sampel_bawahan

        for sampel in sampel_terpilih:
            baris = [nama, tim, jabatan, sampel]

            list_data.append(baris)

Pengerjaan Analisis Statistik
Pengerjaan Tim penyusun publikasi inkesra
Pengerjaan Tim penyusun publikasi sdgs
Pengerjaan Tim Analisis dan Diseminasi Big Data(Data Insights)
Pengerjaan Tim Pengembangan Indikator dan Penjaminan Kualitas Big Data (Statistics Indicator & Quality Assurance)
Pengerjaan Tim penyusun publikasi Indikator Ekonomi
Pengerjaan Tim penyusun publikasi LPI
Pengerjaan Tim Integrasi dan Penyiapan Big Data(Data Engineer)
Pengerjaan EPSS (lintas direktorat)
Pengerjaan FMS
Pengerjaan MK Regsosek
Pengerjaan GB II MK ST2023
Pengerjaan Pembinaan statistik sektoral
Pengerjaan QG ST2023
Pengerjaan SAE MSA
Pengerjaan Pengukuran Kualitas
Pengerjaan PK LF SP2020

In [6]:
# Buat DF

df_jadi = pd.DataFrame(data=list_data, columns=['nama', 'tim', 'jabatan', 'nama_ternilai'])
df_jadi = df_jadi.merge(df_daftar_nama, how='left', left_on=['nama_ternilai', 'tim'], right_on=['Nama', 'Tim'])
df_jadi = df_jadi.drop(columns=['Nama','Tim'])
df_jadi = df_jadi.rename(columns={'Jabatan': 'jabatan_ternilai'})

df_jadi

,nama,tim,jabatan,nama_ternilai,jabatan_ternilai
0,Adi Nugroho SST,Analisis Statistik,Anggota Tim,"Wisnu Winardi SST, ME.",Ketua Tim
1,Adi Nugroho SST,Analisis Statistik,Anggota Tim,Dyah Retno Prihatinningsih B.St,Anggota Tim
2,Adi Nugroho SST,Analisis Statistik,Anggota Tim,"Nur Putri Cahyo Utami SST, M.P.P",Anggota Tim
3,Adi Nugroho SST,Analisis Statistik,Anggota Tim,"Risyanto S.Si, M.Si",Anggota Tim
4,Adi Nugroho SST,Analisis Statistik,Anggota Tim,Dede Yoga Paramartha S.Tr.Stat,Anggota Tim
...,...,...,...,...,...
665,Sa'ad Tazkiahtu Dienulloh SST,PK LF SP2020,Anggota Tim,"Lestyowati Endang Widyantari S.Si, M.Kesos",Ketua Tim
666,Sa'ad Tazkiahtu Dienulloh SST,PK LF SP2020,Anggota Tim,Ria Noviana S.Tr.Stat.,Anggota Tim
667,Sa'ad Tazkiahtu Dienulloh SST,PK LF SP2020,Anggota Tim,Fadlilah Nur Hidayah S.Tr.Stat.,Anggota Tim
668,Sa'ad Tazkiahtu Dienulloh SST,PK LF SP2020,Anggota Tim,Julita Lovitawati Br. Aritonang SST,Anggota Tim
669,Sa'ad Tazkiahtu Dienulloh SST,PK LF SP2020,Anggota Tim,"Rerta Mastiani S.Si, M.Si",Anggota Tim

In [112]:
# Cleaning kalau lebih dari 5 kemudian diambil random
df_clean = pd.DataFrame()
for nama in daftar_nama:
    df_per_nama = df_jadi[df_jadi['nama'] == nama].reset_index(drop=True)
    df_per_nama = df_per_nama.drop_duplicates(subset = ['nama_ternilai']).reset_index(drop=True) # menghapus orang yang menilai orang yang sama berkali2
    jumlah_ternilai = len(df_per_nama)
    # print(f'{nama} - {jumlah_ternilai} orang.')

    if jumlah_ternilai > 5:
        drop_indices = np.random.choice(df_per_nama.index, jumlah_ternilai-5, replace=False)
        df_per_nama = df_per_nama.drop(drop_indices).reset_index(drop=True)


    df_clean = pd.concat([df_clean, df_per_nama], ignore_index=True).reset_index(drop=True)

df_clean

,nama,tim,jabatan,nama_ternilai,jabatan_ternilai
0,Indah Budiati,Tim penyusun publikasi inkesra,Ketua Tim,Tika meilaningsih,Anggota Tim
1,Indah Budiati,Tim penyusun publikasi inkesra,Ketua Tim,Nia setiyawati,Anggota Tim
2,Indah Budiati,Tim penyusun publikasi inkesra,Ketua Tim,Henri A reagan,Anggota Tim
3,Indah Budiati,Tim penyusun publikasi inkesra,Ketua Tim,Adwi hastuti,Anggota Tim
4,Indah Budiati,Tim penyusun publikasi inkesra,Ketua Tim,Nurarifin,Anggota Tim
...,...,...,...,...,...
288,Bayu Dwi Kurniawan S.Tr.Stat.,Analisis Statistik,Anggota Tim,Yoyo Karyono SST,Ketua Tim
289,Bayu Dwi Kurniawan S.Tr.Stat.,Analisis Statistik,Anggota Tim,"Nur Putri Cahyo Utami SST, M.P.P",Anggota Tim
290,Bayu Dwi Kurniawan S.Tr.Stat.,Analisis Statistik,Anggota Tim,"Dimas Hari Santoso S.Si, M.Ec, M.E",Anggota Tim
291,Bayu Dwi Kurniawan S.Tr.Stat.,Analisis Statistik,Anggota Tim,Dewi Widyawati S.Tr.Stat.,Anggota Tim
292,Bayu Dwi Kurniawan S.Tr.Stat.,Analisis Statistik,Anggota Tim,Alvina Clarissa SST,Anggota Tim

In [7]:
# Cleaning kalau lebih dari 5 kemudian diambil semua ketua tim, sisanya random
df_clean = pd.DataFrame()
for nama in daftar_nama:
    df_per_nama = df_jadi[df_jadi['nama'] == nama].reset_index(drop=True)
    df_per_nama = df_per_nama.drop_duplicates(subset = ['nama_ternilai']).reset_index(drop=True)

    # DF yang dinilai adalah ketua tim
    df_per_nama_ketua = df_per_nama[df_per_nama['jabatan_ternilai'] == 'Ketua Tim'].drop_duplicates(subset = ['nama_ternilai']).reset_index(drop=True)
    jumlah_ternilai_ketua = len(df_per_nama_ketua)

    # DF yang dinilai adalah rekan kerja atau bawahan
    df_per_nama_rekan = df_per_nama[df_per_nama['jabatan_ternilai'] != 'Ketua Tim'].drop_duplicates(subset = ['nama_ternilai']).reset_index(drop=True)
    jumlah_ternilai = len(df_per_nama_rekan)

    if jumlah_ternilai_ketua + jumlah_ternilai > 5:
        drop_indices = np.random.choice(df_per_nama_rekan.index, jumlah_ternilai_ketua + jumlah_ternilai - 5, replace=False)
        df_per_nama_rekan = df_per_nama_rekan.drop(drop_indices).reset_index(drop=True)
        # print(f'{nama} - {jumlah_ternilai_ketua} ketua - {jumlah_ternilai} rekan kerja - kurangi {pengurang}')

    df_gabungan = pd.concat([df_per_nama_ketua, df_per_nama_rekan], ignore_index=True).reset_index(drop=True)

    df_clean = pd.concat([df_clean, df_gabungan], ignore_index=True).reset_index(drop=True)

df_clean

,nama,tim,jabatan,nama_ternilai,jabatan_ternilai
0,Adi Nugroho SST,Analisis Statistik,Anggota Tim,"Wisnu Winardi SST, ME.",Ketua Tim
1,Adi Nugroho SST,Analisis Statistik,Anggota Tim,Dyah Retno Prihatinningsih B.St,Anggota Tim
2,Adi Nugroho SST,Analisis Statistik,Anggota Tim,"Nur Putri Cahyo Utami SST, M.P.P",Anggota Tim
3,Adi Nugroho SST,Analisis Statistik,Anggota Tim,"Risyanto S.Si, M.Si",Anggota Tim
4,Adi Nugroho SST,Analisis Statistik,Anggota Tim,Dede Yoga Paramartha S.Tr.Stat,Anggota Tim
...,...,...,...,...,...
275,Zulfa Hidayah Satria Putri SST,Tim Analisis dan Diseminasi Big Data(Data Insi...,Anggota Tim,"Dhiar Niken Larasati SST, M.E.",Ketua Tim
276,Zulfa Hidayah Satria Putri SST,Tim Pengembangan Indikator dan Penjaminan Kual...,Anggota Tim,"Usman Bustaman S.Si, M.Sc",Ketua Tim
277,Zulfa Hidayah Satria Putri SST,Tim Analisis dan Diseminasi Big Data(Data Insi...,Anggota Tim,Ana Lailatul Fitriyani S.Tr.Stat.,Anggota Tim
278,Zulfa Hidayah Satria Putri SST,Tim Analisis dan Diseminasi Big Data(Data Insi...,Anggota Tim,"Yeshri Rahayu S.Si, M.Sc, MT",Anggota Tim
279,Zulfa Hidayah Satria Putri SST,Tim Pengembangan Indikator dan Penjaminan Kual...,Anggota Tim,"Sukmasari Dewanti SST, M.Sc",Anggota Tim

In [8]:
# Tambah kolom bulan
from datetime import date, datetime

currentMonth = datetime.now().month
currentYear = datetime.now().year

df_clean['bulan_penilaian'] = str(currentMonth) + '-' + str(currentYear)

# Tambah kolom nilai
df_clean[['p1', 'p2', 'p3', 'p4', 'p5', 'p6']] = None

df_clean.to_csv('../data/Test Sampling.csv',sep = ';', index=False)
df_clean

,nama,tim,jabatan,nama_ternilai,jabatan_ternilai,bulan_penilaian,p1,p2,p3,p4,p5,p6
0,Adi Nugroho SST,Analisis Statistik,Anggota Tim,"Wisnu Winardi SST, ME.",Ketua Tim,8-2022,None,None,None,None,None,None
1,Adi Nugroho SST,Analisis Statistik,Anggota Tim,Dyah Retno Prihatinningsih B.St,Anggota Tim,8-2022,None,None,None,None,None,None
2,Adi Nugroho SST,Analisis Statistik,Anggota Tim,"Nur Putri Cahyo Utami SST, M.P.P",Anggota Tim,8-2022,None,None,None,None,None,None
3,Adi Nugroho SST,Analisis Statistik,Anggota Tim,"Risyanto S.Si, M.Si",Anggota Tim,8-2022,None,None,None,None,None,None
4,Adi Nugroho SST,Analisis Statistik,Anggota Tim,Dede Yoga Paramartha S.Tr.Stat,Anggota Tim,8-2022,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
275,Zulfa Hidayah Satria Putri SST,Tim Analisis dan Diseminasi Big Data(Data Insi...,Anggota Tim,"Dhiar Niken Larasati SST, M.E.",Ketua Tim,8-2022,None,None,None,None,None,None
276,Zulfa Hidayah Satria Putri SST,Tim Pengembangan Indikator dan Penjaminan Kual...,Anggota Tim,"Usman Bustaman S.Si, M.Sc",Ketua Tim,8-2022,None,None,None,None,None,None
277,Zulfa Hidayah Satria Putri SST,Tim Analisis dan Diseminasi Big Data(Data Insi...,Anggota Tim,Ana Lailatul Fitriyani S.Tr.Stat.,Anggota Tim,8-2022,None,None,None,None,None,None
278,Zulfa Hidayah Satria Putri SST,Tim Analisis dan Diseminasi Big Data(Data Insi...,Anggota Tim,"Yeshri Rahayu S.Si, M.Sc, MT",Anggota Tim,8-2022,None,None,None,None,None,None
279,Zulfa Hidayah Satria Putri SST,Tim Pengembangan Indikator dan Penjaminan Kual...,Anggota Tim,"Sukmasari Dewanti SST, M.Sc",Anggota Tim,8-2022,None,None,None,None,None,None

In [9]:
import mysql.connector as mysql

## UPDATE DATABASE
bulan_penilaian = str(currentMonth) + '-' + str(currentYear)

mydb = mysql.connect(
    host="localhost",
    user="root",
    password="",
    database="if_daps"
)

mycursor = mydb.cursor()

# Hapus data terlebih dahulu
sql_delete = ' DELETE FROM data_penilaian WHERE bulan_penilaian = "'+bulan_penilaian+'" '

mycursor.execute(sql_delete)
mydb.commit()

for index, row in df_clean.iterrows():
    # Masukin ke DB
    sql = "INSERT data_penilaian VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
    baris = (
        row['nama'],
        row['tim'],
        row['jabatan'],
        row['nama_ternilai'],
        row['jabatan_ternilai'],
        row['bulan_penilaian'],
        row['p1'],
        row['p2'],
        row['p3'],
        row['p4'],
        row['p5'],
        row['p6'],
    )

    mycursor.execute(sql, baris)
    mydb.commit()

mydb.close()

In [11]:
nmternilai = df_clean['nama_ternilai'].drop_duplicates().to_list()
nmternilai

['Wisnu Winardi SST, ME.',
 'Dyah Retno Prihatinningsih B.St',
 'Nur Putri Cahyo Utami SST, M.P.P',
 'Risyanto S.Si, M.Si',
 'Dede Yoga Paramartha S.Tr.Stat',
 'Indah Budiati SST, M.Si',
 'Henri Asri Reagan SST., M.Si.',
 'Erna Yulianingsih SST, M.Appl.Ecmets',
 'Nurarifin SST, M.Ec.Dev, M.Ec.',
 'Muhammad Ihsan SST',
 'Yoyo Karyono SST',
 'Adi Nugroho SST',
 'Nurbaety Setram S.Si, M.S.',
 'Dhiar Niken Larasati SST, M.E.',
 'Usman Bustaman S.Si, M.Sc',
 'Maulana Faris SST',
 'Yeshri Rahayu S.Si, M.Sc, MT',
 'I Gusti Ngurah Agung Rama Gunawan SST.,MT',
 'Syukriyah Delyana SST',
 'Alvina Clarissa SST',
 'Sofaria Ayuni S.Si, MM',
 'Tika Meilaningsih S.Tr.Stat.',
 'Maria Audrey Widiatma S.Tr.Stat.',
 'Wahyu Calvin Frans Mariel SST',
 'Nia Setiyawati SST, M.Sc',
 'Dimas Hari Santoso S.Si, M.Ec, M.E',
 'Ana Lailatul Fitriyani S.Tr.Stat.',
 'Khairunnisah SST, M.S.E',
 'Zulfa Hidayah Satria Putri SST',
 'Synthia Natalia Kristiani SST',
 'Lestyowati Endang Widyantari S.Si, M.Kesos',
 'Sukmasari Dewanti SST, M.Sc',
 'Farhan Anshari Arsyi S.Tr.Stat.',
 'Ema Tusianti SST, SAB, M.T., M.Sc',
 'Dewi Widyawati S.Tr.Stat.',
 'Fenny Afifatul Awwaliyah S.Tr.Stat.',
 'Putri Wahyu Handayani SST, M.S.E',
 'Didit Puji Hariyanto SST',
 'Ety Kurniati S.ST',
 'Julita Lovitawati Br. Aritonang SST',
 'Dewi Krismawati SST, M.T.I',
 'Bayu Dwi Kurniawan S.Tr.Stat.',
 'Nensi Fitria Deli SST',
 'Ranu Yulianto SST',
 'Chairul Anam SAP',
 "Sa'ad Tazkiahtu Dienulloh SST",
 'Ria Noviana S.Tr.Stat.',
 'Fadlilah Nur Hidayah S.Tr.Stat.',
 'Satria Bagus Panuntun S.Tr.Stat.',
 'I Nyoman Setiawan S.Tr.Stat.',
 'Rerta Mastiani S.Si, M.Si',
 'Adwi Hastuti SST',
 'Kasiful Aprianto SST',
 'Yohanes Eki Apriliawan SST',
 'Sri Hartini MPS, MA',
 'Dewi Lestari Amaliah SST']

In [12]:
for nm in nmternilai:
    if nm not in daftar_nama:
        print(nm)